# Generated by Django 5.0.6 on 2024-07-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arriendos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='arrendador',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='arrendatario',
        ),
        migrations.AddField(
            model_name='inmueble',
            name='usuarios',
            field=models.ManyToManyField(related_name='inmuebles', to='arriendos.usuario'),
        ),
    ]
