# Generated by Django 5.0.6 on 2024-07-12 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arriendos', '0002_alter_usuario_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nombre_usuario', models.CharField(max_length=64)),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='arriendos.tipousuario'),
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('mensaje', models.TextField(default='¡Estoy interesado!')),
                ('inmueble', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='arriendos.inmueble')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='arriendos.usuario')),
            ],
        ),
    ]
